Table det_compras {
	compra_id integer [ not null ]
	prod_id integer [ not null ]
	id_deposito integer [ not null ]
	det_cantidad integer [ not null ]
	det_precio decimal [ not null ]
	det_subtotal decimal [ not null ]
}

Table compra {
	compra_id integer [ pk, increment, not null, unique ]
	compra_fecha date [ not null ]
	compra_hora time
	emp_id integer [ not null ]
	prov_id integer [ not null ]
	met_id integer [ not null ]
	total decimal [ not null ]
}

Table Ventas {
	venta_id integer [ pk, increment, not null, unique ]
	venta_fecha date [ not null ]
	venta_hora time
	emp_id integer [ not null ]
	cli_id integer [ not null ]
	met_id integer [ not null ]
	total decimal [ not null ]
}

Table empleados {
	emp_id integer [ pk, increment, not null, unique ]
	emp_n... varchar [ not null ]
	emp_ap.. varchar [ not null ]
	emp_ci integer [ not null ]
	emp_tel varchar [ not null ]
	car_id integer [ not null ]
}

Table productos {
	prod_id integer [ pk, increment, not null, unique ]
	prod_... varchar [ not null ]
	prod_precio integer [ not null ]
	prov_id integer [ not null ]
}

Table det_ventas {
	venta_id integer [ not null ]
	prod_id integer [ not null ]
	id_deposito integer [ not null ]
	det_cantidad integer [ not null ]
	det_precio decimal [ not null ]
	det_subtotal decimal [ not null ]
}

Table cargos {
	car_id integer [ pk, increment, not null, unique ]
	car_d... varchar [ not null ]
}

Table clientes {
	clie_id integer [ pk, increment, not null, unique ]
	clie_nom... varchar [ not null ]
	clie_apell.. varchar [ not null ]
	clie_ci integer [ not null ]
}

Table metodo_de_pago {
	met_id integer [ pk, increment, not null, unique ]
	met_de... varchar [ not null ]
}

Table proveedores {
	prov_id integer [ pk, increment, not null, unique ]
	prov_d... varchar [ not null ]
}

Table deposito {
	id_dep serial [ pk, not null, unique ]
	desc_deposito varchar [ not null ]
}

Table deposito_producto {
	id_deposito integer [ pk, increment, not null, unique ]
	id_producto integer [ pk, not null ]
	cantidad integer [ not null ]
}

Ref fk_empleados_emp_id_Ventas {
	empleados.emp_id < Ventas.emp_id [ delete: restrict, update: cascade ]
}

Ref fk_metodo_de_pago_met_id_Ventas {
	metodo_de_pago.met_id < Ventas.met_id [ delete: restrict, update: cascade ]
}

Ref fk_proveedores_prov_id_productos {
	proveedores.prov_id < productos.prov_id [ delete: restrict, update: cascade ]
}

Ref fk_productos_prod_id_det_ventas {
	productos.prod_id < det_ventas.prod_id [ delete: restrict, update: cascade ]
}

Ref fk_cargos_car_id_empleados {
	cargos.car_id < empleados.car_id [ delete: cascade, update: restrict ]
}

Ref fk_clientes_clie_id_Ventas {
	clientes.clie_id < Ventas.cli_id [ delete: restrict, update: cascade ]
}

Ref fk_Ventas_venta_id_det_ventas {
	Ventas.venta_id < det_ventas.venta_id [ delete: restrict, update: cascade ]
}

Ref fk_deposito_id_dep_deposito_producto {
	deposito.id_dep < deposito_producto.id_deposito [ delete: restrict, update: cascade ]
}

Ref fk_productos_prod_id_deposito_producto {
	productos.prod_id < deposito_producto.id_producto [ delete: restrict, update: cascade ]
}

Ref fk_deposito_id_dep_det_ventas {
	deposito.id_dep < det_ventas.id_deposito [ delete: restrict, update: cascade ]
}

Ref fk_metodo_de_pago_met_id_compra {
	metodo_de_pago.met_id < compra.met_id [ delete: restrict, update: cascade ]
}

Ref fk_compra_compra_id_det_compras {
	compra.compra_id < det_compras.compra_id [ delete: restrict, update: cascade ]
}

Ref fk_empleados_emp_id_compra {
	empleados.emp_id < compra.emp_id [ delete: restrict, update: cascade ]
}

Ref fk_proveedores_prov_id_compra {
	proveedores.prov_id < compra.prov_id [ delete: restrict, update: cascade ]
}

Ref fk_productos_prod_id_det_compras {
	productos.prod_id < det_compras.prod_id [ delete: restrict, update: cascade ]
}

Ref fk_deposito_id_dep_det_compras {
	deposito.id_dep < det_compras.id_deposito [ delete: restrict, update: cascade ]
}